server:
  port: ${PORT:4000}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bomberman}
    username: ${DB_USER:bombermanonline}
    password: ${DB_PASSWORD:juanes2026}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: ${JWT_SECRET:bomberman_local_dev_secret_32chars_ok}
    expiration-ms: 28800000
  cors:
    allowed-origin: ${FRONTEND_URL:http://localhost:5174}
  socketio:
    port: ${SOCKETIO_PORT:4001}
    enabled: ${SOCKETIO_ENABLED:false}

logging:
  level:
    com.arsw.bomberman: INFO


